# Generated by Django 5.2.5 on 2025-08-20 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("promoters", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="promoter",
            name="famous_for",
            field=models.CharField(default="", max_length=50),
            preserve_default=False,
        ),
    ]
