# Generated by Django 5.2.5 on 2025-08-20 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('promoters', '0008_promoter_street_address'), ('promoters', '0009_promoter_city_promoter_country_and_more')]

    dependencies = [
        ('promoters', '0006_promoter_birth_squashed_0007_promoter_death'),
    ]

    operations = [
        migrations.AddField(
            model_name='promoter',
            name='city',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='promoter',
            name='country',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='promoter',
            name='postal_zip_code',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='promoter',
            name='province_state',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='promoter',
            name='street_address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
