# Generated by Django 5.2.5 on 2025-08-21 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promoters', '0008_promoter_street_address_squashed_0009_promoter_city_promoter_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='promoter',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
