# Generated by Django 5.2.5 on 2025-08-21 06:56

from django.db import migrations


# def create_full_address(apps, schema_editor):
#     Promoter = apps.get_model("promoters", "Promoter")
#     for promoter in Promoter.objects.all():
#         promoter.address = ", ".join(
#             [
#                 promoter.street_address,
#                 promoter.city,
#                 promoter.province_state,
#                 promoter.country,
#                 promoter.postal_zip_code,
#             ]
#         )
#         promoter.save()


# def split_full_address(apps, schema_editor):
#     Promoter = apps.get_model("promoters", "Promoter")
#     for promoter in Promoter.objects.all():
#         attrs = [
#             "street_address",
#             "city",
#             "province_state",
#             "country",
#             "postal_zip_code",
#         ]

#         full_address_split = promoter.address.split(",")

#         for i, part in enumerate(full_address_split):
#             setattr(promoter, attrs[i], part.strip())

#         promoter.save()


class Migration(migrations.Migration):

    dependencies = [
        ("promoters", "0010_promoter_address"),
    ]

    # operations = [migrations.RunPython(create_full_address, split_full_address)]
    operations = []
