# Generated by Django 5.2.5 on 2025-08-21 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promoters', '0012_remove_promoter_city_remove_promoter_country_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promoter',
            name='address',
        ),
        migrations.AddField(
            model_name='promoter',
            name='city',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='promoter',
            name='country',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='promoter',
            name='postal_zip_code',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='promoter',
            name='province_state',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='promoter',
            name='street_address',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
