# Generated by Django 5.2.5 on 2025-08-21 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promoters', '0013_remove_promoter_address_promoter_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promoter',
            name='city',
        ),
        migrations.RemoveField(
            model_name='promoter',
            name='country',
        ),
        migrations.RemoveField(
            model_name='promoter',
            name='postal_zip_code',
        ),
        migrations.RemoveField(
            model_name='promoter',
            name='province_state',
        ),
        migrations.RemoveField(
            model_name='promoter',
            name='street_address',
        ),
    ]
