# Generated by Django 5.2.5 on 2025-08-18 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0005_venue_description_venue_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='musician',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='musician',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
