# Generated by Django 5.2.5 on 2025-08-20 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0006_musician_description_musician_picture'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='room',
            unique_together=set(),
        ),
    ]
